-- DATE FUNCTIONS
-----------------------------------------
-- SYSDATE

SELECT SYSDATE FROM DUAL;
SELECT SYSDATE+10, SYSDATE-10 FROM DUAL;
SELECT SYSDATE+30, SYSDATE-30 FROM DUAL;

-- ADD_MONTHS

SELECT ADD_MONTHS(SYSDATE,2), ADD_MONTHS(SYSDATE,-1) FROM DUAL;


select ename from emp where instr(ename, substr(ename,1,1),1,2)<>0;

define  V1='TWINKLE TWINKLE LITTLE STAR';

SELECT LENGTH('&V1') FROM DUAL;
SELECT LENGTH(REPLACE('&V1', 'T', NULL)) FROM DUAL;

SELECT LENGTH('&V1') - LENGTH(REPLACE('&V1', 'T', NULL)) "Count"  FROM DUAL;
select REGEXP_COUNT('&V1', '[T]') "Count OF T" FROM DUAL;


SELECT ENAME, HIREDATE, (SYSDATE-HIREDATE) "DIFF" FROM EMP;
SELECT ENAME, HIREDATE, (SYSDATE-HIREDATE) "DIFF", ((SYSDATE-HIREDATE)/30) "MONTHS" FROM EMP;

SELECT ENAME, HIREDATE, (SYSDATE-HIREDATE) "DIFF", ROUND((SYSDATE-HIREDATE)/30,2) "MONTHS",
MONTHS_BETWEEN(SYSDATE-HIREDATE) "USING func"  FROM EMP;

SELECT LAST_DAY(SYSDATE) FROM DUAL;

select NEXT_DAY(SYSDATE, 'THURSDAY') FROM DUAL;

--DISPLAYS 1ST FRIDAY DATE FROM LAST MONTH
SELECT NEXT_DAY(LAST_DAY(ADD_MONTHS(SYSDATE,-1)), 'FRI') FROM DUAL;


select ROUND(SYSDATE) "DAYWISE", ROUND(SYSDATE,'MONTH') "MONTHWISE", ROUND(SYSDATE, 'YEAR') "YEARWISE" FROM DUAL;

select TRUNC(SYSDATE) "DAYWISE", TRUNC(SYSDATE,'MONTH') "MONTHWISE", TRUNC(SYSDATE, 'YEAR') "YEARWISE" FROM DUAL;



