/* 
MULTIPLE ROW FUNCTIONS
----------------------------
AGGREGATE FUNCTIONS

COUNT() - COUNTS THE NO OF ROWS
          COUNT(*) - INCLUDES NULL VALUES TOO
          COUNT(COLUMNNAME) - DOESNT INCLUDE NULL VALUES
MIN()
MAX()
AVG()
SUM()

*/


select ENAME, DEPTNO FROM EMP  WHERE DEPTNO=30;
SELECT COUNT(*) FROM EMP;
SELECT COUNT(*) FROM EMP WHERE DEPTNO=30;
SELECT COUNT(*), COUNT(ENAME), COUNT(COMM) FROM EMP ;

SELECT MIN(SAL) FROM EMP WHERE JOB='SALESMAN';
SELECT MIN(ENAME), MIN(SAL), MIN(HIREDATE) FROM EMP;
SELECT MAX(ENAME), MAX(SAL), MAX(HIREDATE), MAX(EMPNO) FROM EMP;
SELECT COUNT(*), MIN(SAL), MAX(SAL), SUM(SAL), ROUND(AVG(SAL),2),  ROUND(SUM(SAL)/COUNT(*), 2) FROM EMP;

-- TO FIND TOTAL SAL FOR EACH DEPT
SELECT SUM(SAL), DEPTNO
FROM EMP
GROUP BY DEPTNO;

-- FIND NO OF EMP IN EACH JOB
SELECT COUNT(*), JOB
FROM EMP
GROUP BY JOB;
--FIND OUT NO OF EMP JOINED DAYWISE
SELECT COUNT(*), TO_CHAR(HIREDATE,'DD')
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'DD');


--FIND OUT NO OF EMP JOINED MONTHWISE
SELECT COUNT(*), TO_CHAR(HIREDATE,'MM')
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'MM');
SELECT COUNT(*), TO_CHAR(HIREDATE,'MONTH') "MON"
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'MONTH')
ORDER BY "MON";

--FIND OUT NO OF EMP JOINED YEARWISE
SELECT COUNT(*), TO_CHAR(HIREDATE,'YY')
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'YY');

--FIND OUT NO OF EMP JOINED QUARTERWISE
SELECT COUNT(*), TO_CHAR(HIREDATE,'Q') "TOCHAR"
FROM EMP
GROUP BY TO_CHAR(HIREDATE,'Q')
ORDER BY "TOCHAR";

