/*
SUBQUERIES
-------------
 > SELECT INSIDE SELECT
 > EVALUVATING UNKNOWN WITH KNOWN
 
 RULES:
 -----------
 > SUBQUERIES EXECUTES FIRST
 > OUTPUT WILL BE USED BY MAIN QUERY AND GETS EXCLUDED
 > SUBQUERY SHOULD BE ENCLOSED IN BRACKETS
 
 TYPES:
 ------------
 SINGLE ROW
 MULTIPLE ROW
 MULTIPLE COLUMN
 NESTED
 CORRELATED
 
 SINGLE ROW :                       MULTIPLE ROW 
---------------------------------------------=--
 > QUERY RETURNS SINGLE ROW         > QUERY RETURNS MULTIPLE ROWS
 
 
*/


-- FIND OUT EMP WHO IS TAKING MAX SAL
SELECT MAX(SAL) FROM EMP;
SELECT ename, sal from EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP);

-- FIND OUT EMP WHO TAKING MORE SAL THAN 'ADAMS'
SELECT SAL FROM EMP WHERE ENAME='ADAMS';

SELECT ENAME, SAL FROM EMP
WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='ADAMS');

-- FIND NAME OF DEPT DNAME IN WHICH TURNER IS WORKING

SELECT DEPTNO FROM EMP WHERE ENAME='TURNER';
SELECT DNAME FROM DEPT
WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='TURNER');

SELECT * FROM EMP;
SELECT * FROM DEPT;

-- FIND EMP REPORTING TO BLAKE
SELECT EMPNO FROM EMP WHERE ENAME='BLAKE';
SELECT ENAME FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='BLAKE');

SELECT E.ENAME, M.ENAME
FROM EMP E JOIN EMP M
ON E.MGR = M.EMPNO
AND M.ENAME='BLAKE';

--FIND OUT SENIORMOST EMPLOYEE
SELECT ENAME FROM EMP WHERE HIREDATE=(SELECT MIN(HIREDATE) FROM EMP);

-- FIND EMPS  WHO WORK AS SAME JOB AS ALLEN

SELECT ENAME FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='ALLEN')
AND ENAME<> 'ALLEN';

-- FIND EMP WHO HAVE JOINED IN THE SAME YEAR AS SCOTT, MARTIN
SELECT ENAME, HIREDATE FROM EMP
WHERE TO_CHAR(HIREDATE,'YYYY') IN (SELECT TO_CHAR(HIREDATE,'YYYY') FROM EMP WHERE ENAME IN ('SCOTT', 'MARTIN'))
AND ENAME NOT IN('SCOTT', 'MARTIN');
