/*
SUBQUERIES
-------------
 > SELECT INSIDE SELECT
 > EVALUVATING UNKNOWN WITH KNOWN
 
 RULES:
 -----------
 > SUBQUERIES EXECUTES FIRST
 > OUTPUT WILL BE USED BY MAIN QUERY AND GETS EXCLUDED
 > SUBQUERY SHOULD BE ENCLOSED IN BRACKETS
*/


-- FIND OUT EMP WHO IS TAKING MAX SAL
SELECT
